alert("variable adalah tempat untuk menyimpan data / value dari sebuah program");
alert("pada pemograman javascript variable dapat ditulis dengan keyword let, var, const.");
alert("let digunakan untuk variable yang bisa diubah");
alert("var digunakan untuk variable yang bisa diubah");
alert("const digunakan untuk variable yang tidak bisa diubah");
alert("contoh var x = 10");
alert("contoh let y = 10");
alert("contoh const z = 10");
alert("ada aturan dalam penulisan nama variable yakni : nama variable tidak boleh diawali angka, mengandung spasi, mengandung karakter spesial, dan tidak boleh sama dengan nama function");
alert("ada beberapa penulisan nama variable yakni camelCase, PascalCase, kebab-case, dan snake_case");
alert("camelCase adalah penulisan nama variable yang mengandung spasi, dan setiap kata mulai dengan huruf besar");
alert("contoh camelCase : firstName, lastName, maxLength");
alert("PascalCase adalah penulisan nama variable yang mengandung spasi, dan setiap kata mulai dengan huruf besar");
alert("contoh PascalCase : FirstName, LastName, MaxLength");
alert("kebab-case adalah penulisan nama variable yang mengandung spasi, dan setiap kata mengandung huruf kecil");
alert("contoh kebab-case : first-name, last-name, max-length");
alert("snake_case adalah penulisan nama variable yang mengandung spasi, dan setiap kata mengandung huruf kecil");
