alert("kita dapat menampilkan data dengan menggunakan alert atau console.log lalu untuk menentukan tipe data sebuah variable dapat menggunakan suatu perintah typeof()");
alert("kalimat merupakan tipe data : " + typeof "kata");
alert("angka merupakan tipe data : " + typeof 10);
alert("boolean merupakan tipe data : " + typeof true);
alert("object merupakan tipe data : " + typeof {});
alert("function merupakan tipe data : " + typeof function () {});
alert("undefined merupakan tipe data : " + typeof undefined);
alert("null merupakan tipe data : " + typeof null);
alert("symbol merupakan tipe data : " + typeof Symbol("symbol"));
alert("bigint merupakan tipe data : " + typeof 10n);
